= Maven artifacts for Eclipse EMF

This repository contains the maven artifacts necessary to build and release Eclipse http://wiki.eclipse.org/EMF[EMF] plugins and features
onto https://bintray.com[Bintray] or to simply build it on your machine.

The builds on Bintray are available https://dl.bintray.com/atlanmod/unveil[here].

== Available versions

|===
| Unveil EMF Version | Eclipse EMF Version | Eclipse Version

| 2.23.x
| 2.23
| 2020-12

| 2.15.x
| 2.15
| Oxygen
|===

== Usage

Add the following repository to your `pom.xml` and then choose which EMF dependencies you want to use in your Maven project:

[source, xml]
----
    <repositories>
        <!-- (...) -->
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-atlanmod</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/atlanmod/unveil</url>
        </repository>
    </repositories>
----

== Eclipse EMF Artifacts

.EMF Common Dependency
[source, xml]
----
<dependency>
    <groupId>org.atlanmod.unveil</groupId>
    <artifactId>org.eclipse.emf.common</artifactId>
    <type>pom</type>
    <version>${unveil.emf.version}</version>
</dependency>
----

.EMF Ecore Dependency
[source, xml]
----
<dependency>
    <groupId>org.atlanmod.unveil</groupId>
    <artifactId>org.eclipse.emf.ecore</artifactId>
    <type>pom</type>
    <version>${unveil.emf.version}</version>
</dependency>
----

.EMF Edit
[source, xml]
----
<dependency>
    <groupId>org.atlanmod.unveil</groupId>
    <artifactId>org.eclipse.emf.edit</artifactId>
    <type>pom</type>
    <version>${unveil.emf.version}</version>
</dependency>
----

.EMF Codegen
[source, xml]
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.codegen</artifactId>
    <type>pom</type>
    <version>${unveil.emf.version}</version>
</dependency>
----


== Build steps

=== Versioning

When building you should first make sure that the pom and manifest versions are compatible.

When pom versions end with `-SNAPSHOT`, `Bundle-Version` in all MANIFEST.MF files should end with `.qualifier`.
When pom versions don't have `-SNAPSHOT`, remove `.qualifier` in MANIFEST files.

=== Building

You can build it yourself with following command inside the cdo-maven folder:

```
$ mvn clean install
```

=== Releasing

> Only for contributors.

Before releasing on maven central, make sure that pom versions end with `-SNAPSHOT` and
MANIFEST versions *do not end* with `.qualifier`, but have the correct release version number.

To release on Bintray, execute:

[source,shell]
----
mvn release:clean release:prepare
----

followed by:

[source,shell]
----
mvn release:perform
----

=== Update POM and MANIFEST.MF versions

[source,shell]
----
mvn versions:set -DnewVersion=2.23.1-SNAPSHOT -DautoVersionSubmodules=true
mvn -f unveil-emf-repackaged tycho-versions:set-version -D newVersion=2.23.1-SNAPSHOT
mvn -f unveil-emf-repackaged tycho-versions:update-eclipse-metadata
----
