= Maven artifacts for Eclipse EMF, Facet, and OCL

This repository contains the maven files necessary to build and release Eclipse http://wiki.eclipse.org/EMF[EMF],
https://wiki.eclipse.org/EMF_Facet[Facet], and http://wiki.eclipse.org/ocl/[OCL]
onto https://bintray.com[Bintray] or to simply build it on your machine.

The builds on Bintray are available https://dl.bintray.com/sunye/AtlanMod[here].

== Usage

Add the following repository to your `pom.xml` and then choose which EMF dependencies you want to use in your maven project:

[source, xml]
----
    <repositories>
        <!-- (...) -->
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-atlanmod</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/sunye/AtlanMod</url>
        </repository>
    </repositories>
----

=== EMF Facet

Include all EMF Facet features

[source,xml
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.facet</artifactId>
    <type>pom</type>
    <version>1.0.2</version>
</dependency>
----

=== Eclipse OCL

Includes OCL, OCL Ecore and OCL UML.

[source,xml]
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.ocl</artifactId>
    <version>1.0.2</version>
    <type>pom</type>
</dependency>
-----

=== EMF Validation

Includes all EMF Validation features.

[source,xml]
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.validation</artifactId>
    <version>1.0.2</version>
    <type>pom</type>
</dependency>
-----

=== EMF Transaction

Includes all EMF Transaction features.

[source,xml]
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.transaction</artifactId>
    <version>1.0.2</version>
    <type>pom</type>
</dependency>
-----


=== Eclipse EMF Artifacts

[source, xml]
----
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf</artifactId>
    <type>pom</type>
    <version>${atlanmod.emf.version}</version>
</dependency>
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.common</artifactId>
    <type>pom</type>
    <version>${atlanmod.emf.version}</version>
</dependency>
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.ecore</artifactId>
    <type>pom</type>
    <version>${atlanmod.emf.version}</version>
</dependency>
<dependency>
    <groupId>org.atlanmod.emf</groupId>
    <artifactId>org.eclipse.emf.edit</artifactId>
    <type>pom</type>
    <version>${atlanmod.emf.version}</version>
</dependency>
----


== Build steps

=== Versioning

When building you should first make sure that the pom and manifest versions are compatible.

When pom versions end with `-SNAPSHOT`, `Bundle-Version` in al MANIFEST.MF files should end with `.qualifier`.
When pom versions don't have `-SNAPSHOT`, remove `.qualifier` in MANIFEST files.

=== Building

You can build it yourself with following command inside the cdo-maven folder:

```
$ mvn clean install
```

=== Releasing

> Only for contributors.

Before releasing on maven central, make sure that pom versions end with `-SNAPSHOT` and
MANIFEST versions <i>do not end</i> with `.qualifier`, but have the correct release version number.

To release on Bintray, execute:

```
mvn release:clean release:prepare
```

followed by:

```
mvn release:perform
```
